name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: ${{ matrix.implementation }} tests (${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        implementation: [ python, cython ]
        exclude:
          - os: macos-latest
            implementation: cython
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30

      - name: Generate cache key
        run: |
          nixpkgs_hash=$(grep -Eo 'archive/[0-9a-f]{40}\.tar\.gz' shell.nix | cut -d'/' -f2 | cut -d'.' -f1)
          echo "NIXPKGS_HASH=$nixpkgs_hash" >> $GITHUB_ENV
          echo "CACHE_KEY=${{ runner.os }}-$nixpkgs_hash" >> $GITHUB_ENV

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ env.CACHE_KEY }}

      - name: Setup NIX_PATH
        run: |
          path=$(nix eval --impure --expr "(import (fetchTarball \"https://github.com/NixOS/nixpkgs/archive/${{ env.NIXPKGS_HASH }}.tar.gz\") {}).path")
          echo "NIX_PATH=nixpkgs=$path" >> $GITHUB_ENV

      - name: Cache files and packages
        uses: actions/cache@v4
        with:
          key: pkg-${{ env.CACHE_KEY }}-${{ hashFiles('uv.lock', 'bun.lock') }}
          path: |
            ~/.cache/uv
            ~/.bun/install/cache
            .venv
            node_modules
            app/static/img/element/_generated
            config/locale/gnu
            config/locale/i18next
            config/locale/postprocess

      - name: Build Cython modules
        if: matrix.implementation == 'cython'
        run: |
          nix-shell --pure --run "cython-build-fast"

      - name: Start services
        run: |
          nix-shell --pure --run "dev-start"

      - name: Run tests (fictional change for trigger CI)
        run: |
          nix-shell --pure --run "run-tests --extended --term"
